protocolbuffers/protobuf-javascript

.github/workflows/codeql.yml

We have both a C++ protoc plugin and JS code (everything
else). Consequently, we need to actually build the protoc plugin so
that we can actually do anything worthwile. This change scripts
download a prepared protoc release and running through the necessary
protobuf-javascript setup actions.

Switch codeql from autobuild to custom commands

---

.github/workflows/codeql.yml

Best practice is to set top level to read only in case more jobs are added to the file later.
This fixes a code scanning alert.

set top level permissions to read

---

binary/decoder_test.js
binary/encoder.js

The javascript serializeBinary() function silently tosses away any non-string placed into what should be a string field, writing the equivalent of an empty string instead
Not sure if or why anyone would be relying on that existing arbitrary behavior today, but silent data loss seems very undesirable and worth defending against
This PR was previously sent at https://github.com/protocolbuffers/protobuf/pull/9584 in the older repo

Catch non-strings in BinaryEncoder.writeString

---

generator/js_generator.cc

Closes https://github.com/protocolbuffers/protobuf-javascript/issues/8. Fixes the issue by explicitly checking if window is defined.
> NOTE: This PR is similar to the old repo PR https://github.com/protocolbuffers/protobuf/pull/9156 by @MarnixBouhuis

fix: #8 window is undefined error

---

WORKSPACE
generator/js_generator.cc
generator/well_known_types_embed.cc

I've also tested this using v21.4 (the latest release) but did not test any releases between those two.
I tested using:
```sh
$ npm install
$ bazel build @com_google_protobuf//:protoc
$ PROTOC="$(realpath bazel-bin/external/com_google_protobuf/protoc)" PROTOC_INC="$(realpath bazel-protobuf-javascript/external/com_google_protobuf/src/)" npm test
```
It may also make sense to update the version of protobuf-javascript here to match the version of protobuf.

Support protobuf v21.0 rc1

---

README.md

While we are still limited due to staffing we should advertise that we are amenable to more contiributions.
Due to our limited support resources, we are focusing our attention on small bug fixes that have limited compatibility concerns. Most other PRs will be rejected.

Clarify our contribution policy

---

binary/decoder.js
binary/decoder_test.js

This fixes https://github.com/protocolbuffers/protobuf-javascript/issues/31

Fix decoding of signed varint32s.

---

asserts.js
package.json

Came across a couple stragglers while doing a dry run of the npm release.

Fix typos in asserts add LICENSE-asserts.md to package.json

---

generator/js_generator.cc

This makes the code cleaner and also fixes a bunch of signedness warnings from GCC.
Due to our limited support resources, we are focusing our attention on small bug fixes that have limited compatibility concerns. Most other PRs will be rejected.

Use range-based for loops in the generator.

---

README.md

Current options link points to a deleted file, updated README to use file from this repo.

Fix outdated options link

---

.github/workflows/build.yml
.github/workflows/codeql.yml
MODULE.bazel
WORKSPACE

As mentioned in the Bazel blog article, the old `WORKSPACE` system is planned to be disabled by default in Bazel 8, and to be removed altogether in Bazel 9.  The `WORKSPACE` file will eventually be removed, but for now, it’s best to keep the dependency versions in both systems in sync, so that we can build the project with Bzlmod either disabled or enabled.
Note that there is a compatibility issue that prevents this project from depending on protobuf v22 and higher.  Until that issue is fixed, v21.7 is the highest version that works with both systems.
References:
- [Bazel Blog › Bazel 7.0 TLS › Bzlmod](https://blog.bazel.build/2023/12/11/bazel-7-release.html#bzlmod)
- [protobuf in BCR](https://registry.bazel.build/modules/protobuf)
- …

Keep dependency versions in sync for `WORKSPACE` and `MODULE.bazel`

---

.github/workflows/build.yml
.github/workflows/codeql.yml
MODULE.bazel
WORKSPACE
generator/js_generator.cc
generator/js_generator.h

This PR updates the code in protobuf-javascript to compile against the latest protobuf versions.
This primarily entails:
- Using absl:: methods instead of the previous vendored ones in Protobuf
- Explicitly using legacy descriptors when important properties are missing
- Explicitly deleting constructors rather than relying on the deleted `GOOGLE_DISALLOW_EVIL_CONSTRUCTORS`

Update protobuf-javascript to support Protobuf 25.2

---

.github/workflows/build.yml
.github/workflows/codeql.yml
MODULE.bazel
MODULE.bazel.lock
WORKSPACE
generator/js_generator.cc
yarn.lock

The protobuf descriptor API has evolved to remove access to the schema's `syntax` and direct access to a oneof's synthetic-ness.
Fixes #206

Update 'syntax' and synthetic oneof to support protobuf 27.1

---

WORKSPACE

Internal release process showing a sha256 digest error. Re-downloaded protobuf zip and recomputed. New digest appears to match what internal tooling expects.

Fix sha256 digest for protobuf http_archive

---

.github/workflows/build.yml
protobuf_javascript_release.bzl

bazelbuild/setup-bazelisk is archived. We need to update for node20 support, so taking the opportunity to migrate (as directed) to bazel-contrib/setup-bazel.

Switch to bazel-contrib/setup-bazel

---

MODULE.bazel
WORKSPACE

In the process of trying to run our release workflow, I discovered a few issues. Verified using `USE_BAZEL_VERSION=6.3.0 BAZEL_CXXOPTS="-std=c++14" bazel build //:dist_all` (under bazelisk).

Fixup WORKSPACE and MODULE.bazel to prepare for release

---

generator/BUILD.bazel
generator/js_generator.cc
generator/js_generator.h
yarn.lock

Added some missing deps on protobuf compiler, io, and some absl string libraries. Also removed some porting related definitions that are internal to protobuf.
Fixes #214

fix generator build layering by correcting deps

---

.github/workflows/build.yml

Updating:
* actions/upload-artifact@v3 ->  4
* actions/checkout@3 ->4
* actions/download-artifact@v3 -> 4

Update various workflow action versions for node 20 compatibility

---

binary/decoder.js
binary/decoder_test.js
binary/reader.js
binary/utf8.js
generator/js_generator.cc
gulpfile.js

Port fix: Fix JSPB binary utf8 decoding and validate by default (breaking change)

---

binary/decoder.js
binary/utf8.js

This change fixes some minor build issues from not using fully specified function names. There was also a missing parameter issue for BinaryDecoder.readStringWithLength's invocation of readString, but the former appears to be dead code so just removed it.

Fix build errors from utf8 enforcement changes

---

.github/workflows/build.yml

actions/upload-artifact@4 made a breaking change to fail on duplicate names. I think we are seeing Windows release errors as a result since both x64_x86 and x64 are named 'releases'.
This change just tags the os and cpu onto the release dir name to reflect the specific build.

Specify os and cpu for release name to avoid duplicates

---

protobuf_javascript_release.bzl

We use PackageVariablesInfo from rules_pkg for versioning. The previous change bumped the version of our rules_pkg dependency and it looks like that moved the declaring providers.bzl file change to a `pkg/` subdir.
This broke our Windows builds/release automation since they use //:dist_zip. We did not catch this during PR testing because we just do `npm test`.

Fix path for rules_pkg providers.bzl load

---

generator/js_generator.cc
jasmine.json

Previously, we blanket ignored extensions against the descriptor well known type for historical reasons. We marked this for cleanup in #85; this change follows through on it.

Do not ignore descriptor extensions

---

.github/workflows/build.yml
package-lock.json
package.json
protobuf_javascript_release.bzl
yarn.lock

Notable inclusions:
* edition 2023 support
* improved binary serialization/deserialization
* global result now only depends on globalThis
There are no material changes to our JS API. However, serialization/deserialization and strict dependence on globalThis may be significant in terms of supported clients and behavior.
We generally expect the new binary handling code to be more reliable and conformant.

Prepare 4.0.0 release

---

.github/workflows/build.yml

We generally do some manual QA on binaries prior to actually posting them. Additionally, we use multiple approaches for building, so it's easier to collect all variants in one location first.

Remove (unused) release step of build.yml
